[workspace]
authors = ["George Filholm <george.filholm@wsu.edu>"]
channels = ["conda-forge"]
name = "581FinalProject"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytest = ">=9.0.2,<10"
python = ">=3.14.2,<3.15"
mystmd = ">=1.7.0,<2"
numpy = ">=2.3.5,<3"
